// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/velopack.dart';
import 'core/dart_types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class VelopackRustLib extends BaseEntrypoint<VelopackRustLibApi,
    VelopackRustLibApiImpl, VelopackRustLibWire> {
  @internal
  static final instance = VelopackRustLib._();

  VelopackRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    VelopackRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required VelopackRustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<VelopackRustLibApiImpl, VelopackRustLibWire>
      get apiImplConstructor => VelopackRustLibApiImpl.new;

  @override
  WireConstructor<VelopackRustLibWire> get wireConstructor =>
      VelopackRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiVelopackInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -175272312;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'velopack_flutter',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class VelopackRustLibApi extends BaseApi {
  Stream<int> crateApiVelopackCheckAndDownloadUpdatesWithProgress(
      {String? channel, bool? allowDowngrade});

  Future<String> crateApiVelopackCurrentVersion();

  Future<UpdateInfo?> crateApiVelopackGetLatestUpdateInfo(
      {String? channel, bool? allowDowngrade});

  Future<void> crateApiVelopackInitApp();

  Future<void> crateApiVelopackInitVelopack(
      {required String url, String? channel, required bool allowDowngrade});

  Future<bool> crateApiVelopackIsUpdateAvailable(
      {String? channel, bool? allowDowngrade});

  Future<void> crateApiVelopackUpdateAndExit(
      {String? channel, bool? allowDowngrade});

  Future<void> crateApiVelopackUpdateAndRestart(
      {String? channel, bool? allowDowngrade});

  Future<void> crateApiVelopackWaitExitThenUpdate(
      {required bool silent,
      required bool restart,
      String? channel,
      bool? allowDowngrade});
}

class VelopackRustLibApiImpl extends VelopackRustLibApiImplPlatform
    implements VelopackRustLibApi {
  VelopackRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<int> crateApiVelopackCheckAndDownloadUpdatesWithProgress(
      {String? channel, bool? allowDowngrade}) {
    final progressSink = RustStreamSink<int>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_i_16_Sse(progressSink, serializer);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_update_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackCheckAndDownloadUpdatesWithProgressConstMeta,
      argValues: [progressSink, channel, allowDowngrade],
      apiImpl: this,
    )));
    return progressSink.stream;
  }

  TaskConstMeta
      get kCrateApiVelopackCheckAndDownloadUpdatesWithProgressConstMeta =>
          const TaskConstMeta(
            debugName: "check_and_download_updates_with_progress",
            argNames: ["progressSink", "channel", "allowDowngrade"],
          );

  @override
  Future<String> crateApiVelopackCurrentVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackCurrentVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackCurrentVersionConstMeta =>
      const TaskConstMeta(
        debugName: "current_version",
        argNames: [],
      );

  @override
  Future<UpdateInfo?> crateApiVelopackGetLatestUpdateInfo(
      {String? channel, bool? allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_update_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackGetLatestUpdateInfoConstMeta,
      argValues: [channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackGetLatestUpdateInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_latest_update_info",
        argNames: ["channel", "allowDowngrade"],
      );

  @override
  Future<void> crateApiVelopackInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVelopackInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiVelopackInitVelopack(
      {required String url, String? channel, required bool allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_opt_String(channel, serializer);
        sse_encode_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackInitVelopackConstMeta,
      argValues: [url, channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackInitVelopackConstMeta =>
      const TaskConstMeta(
        debugName: "init_velopack",
        argNames: ["url", "channel", "allowDowngrade"],
      );

  @override
  Future<bool> crateApiVelopackIsUpdateAvailable(
      {String? channel, bool? allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackIsUpdateAvailableConstMeta,
      argValues: [channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackIsUpdateAvailableConstMeta =>
      const TaskConstMeta(
        debugName: "is_update_available",
        argNames: ["channel", "allowDowngrade"],
      );

  @override
  Future<void> crateApiVelopackUpdateAndExit(
      {String? channel, bool? allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackUpdateAndExitConstMeta,
      argValues: [channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackUpdateAndExitConstMeta =>
      const TaskConstMeta(
        debugName: "update_and_exit",
        argNames: ["channel", "allowDowngrade"],
      );

  @override
  Future<void> crateApiVelopackUpdateAndRestart(
      {String? channel, bool? allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackUpdateAndRestartConstMeta,
      argValues: [channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackUpdateAndRestartConstMeta =>
      const TaskConstMeta(
        debugName: "update_and_restart",
        argNames: ["channel", "allowDowngrade"],
      );

  @override
  Future<void> crateApiVelopackWaitExitThenUpdate(
      {required bool silent,
      required bool restart,
      String? channel,
      bool? allowDowngrade}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(silent, serializer);
        sse_encode_bool(restart, serializer);
        sse_encode_opt_String(channel, serializer);
        sse_encode_opt_box_autoadd_bool(allowDowngrade, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVelopackWaitExitThenUpdateConstMeta,
      argValues: [silent, restart, channel, allowDowngrade],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVelopackWaitExitThenUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "wait_exit_then_update",
        argNames: ["silent", "restart", "channel", "allowDowngrade"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_16_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  UpdateInfo dco_decode_box_autoadd_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_info(raw);
  }

  @protected
  VelopackAsset dco_decode_box_autoadd_velopack_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_velopack_asset(raw);
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VelopackAsset> dco_decode_list_velopack_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_velopack_asset).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  UpdateInfo? dco_decode_opt_box_autoadd_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_update_info(raw);
  }

  @protected
  VelopackAsset? dco_decode_opt_box_autoadd_velopack_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_velopack_asset(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateInfo dco_decode_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UpdateInfo(
      targetFullRelease: dco_decode_velopack_asset(arr[0]),
      baseRelease: dco_decode_opt_box_autoadd_velopack_asset(arr[1]),
      deltasToTarget: dco_decode_list_velopack_asset(arr[2]),
      isDowngrade: dco_decode_bool(arr[3]),
    );
  }

  @protected
  VelopackAsset dco_decode_velopack_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return VelopackAsset(
      packageId: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      type: dco_decode_String(arr[2]),
      fileName: dco_decode_String(arr[3]),
      sha1: dco_decode_String(arr[4]),
      sha256: dco_decode_String(arr[5]),
      size: dco_decode_u_64(arr[6]),
      notesMarkdown: dco_decode_String(arr[7]),
      notesHtml: dco_decode_String(arr[8]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_16_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  UpdateInfo sse_decode_box_autoadd_update_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_info(deserializer));
  }

  @protected
  VelopackAsset sse_decode_box_autoadd_velopack_asset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_velopack_asset(deserializer));
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VelopackAsset> sse_decode_list_velopack_asset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VelopackAsset>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_velopack_asset(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UpdateInfo? sse_decode_opt_box_autoadd_update_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_update_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VelopackAsset? sse_decode_opt_box_autoadd_velopack_asset(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_velopack_asset(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateInfo sse_decode_update_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_targetFullRelease = sse_decode_velopack_asset(deserializer);
    var var_baseRelease =
        sse_decode_opt_box_autoadd_velopack_asset(deserializer);
    var var_deltasToTarget = sse_decode_list_velopack_asset(deserializer);
    var var_isDowngrade = sse_decode_bool(deserializer);
    return UpdateInfo(
        targetFullRelease: var_targetFullRelease,
        baseRelease: var_baseRelease,
        deltasToTarget: var_deltasToTarget,
        isDowngrade: var_isDowngrade);
  }

  @protected
  VelopackAsset sse_decode_velopack_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_packageId = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_type = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_sha1 = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_notesMarkdown = sse_decode_String(deserializer);
    var var_notesHtml = sse_decode_String(deserializer);
    return VelopackAsset(
        packageId: var_packageId,
        version: var_version,
        type: var_type,
        fileName: var_fileName,
        sha1: var_sha1,
        sha256: var_sha256,
        size: var_size,
        notesMarkdown: var_notesMarkdown,
        notesHtml: var_notesHtml);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_i_16_Sse(
      RustStreamSink<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_i_16,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_info(
      UpdateInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_velopack_asset(
      VelopackAsset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_velopack_asset(self, serializer);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_velopack_asset(
      List<VelopackAsset> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_velopack_asset(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_update_info(
      UpdateInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_update_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_velopack_asset(
      VelopackAsset? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_velopack_asset(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_info(UpdateInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_velopack_asset(self.targetFullRelease, serializer);
    sse_encode_opt_box_autoadd_velopack_asset(self.baseRelease, serializer);
    sse_encode_list_velopack_asset(self.deltasToTarget, serializer);
    sse_encode_bool(self.isDowngrade, serializer);
  }

  @protected
  void sse_encode_velopack_asset(VelopackAsset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.packageId, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.type, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.sha1, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.notesMarkdown, serializer);
    sse_encode_String(self.notesHtml, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
