// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/dart_types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_and_download_updates`, `get_update_manager`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VelopackConfig`

Future<void> initVelopack(
        {required String url, String? channel, required bool allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackInitVelopack(
        url: url, channel: channel, allowDowngrade: allowDowngrade);

Future<bool> isUpdateAvailable({String? channel, bool? allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackIsUpdateAvailable(
        channel: channel, allowDowngrade: allowDowngrade);

Future<UpdateInfo?> getLatestUpdateInfo(
        {String? channel, bool? allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackGetLatestUpdateInfo(
        channel: channel, allowDowngrade: allowDowngrade);

Future<String> currentVersion() =>
    VelopackRustLib.instance.api.crateApiVelopackCurrentVersion();

Stream<int> checkAndDownloadUpdatesWithProgress(
        {String? channel, bool? allowDowngrade}) =>
    VelopackRustLib.instance.api
        .crateApiVelopackCheckAndDownloadUpdatesWithProgress(
            channel: channel, allowDowngrade: allowDowngrade);

Future<void> updateAndRestart({String? channel, bool? allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackUpdateAndRestart(
        channel: channel, allowDowngrade: allowDowngrade);

Future<void> updateAndExit({String? channel, bool? allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackUpdateAndExit(
        channel: channel, allowDowngrade: allowDowngrade);

Future<void> waitExitThenUpdate(
        {required bool silent,
        required bool restart,
        String? channel,
        bool? allowDowngrade}) =>
    VelopackRustLib.instance.api.crateApiVelopackWaitExitThenUpdate(
        silent: silent,
        restart: restart,
        channel: channel,
        allowDowngrade: allowDowngrade);
